import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { AccountStore } from '../src/service/account-store.js';
import { JobStore } from '../src/service/job-store.js';
import { startService } from '../src/service/server.js';

test('paid single migration grants and consumes exactly one durable credit', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'repo-upgrader-paid-flow-'));
  const store = await new JobStore(path.join(root, 'jobs.json')).load();
  const accountStore = await new AccountStore(path.join(root, 'accounts.json')).load();
  const secret = 'billing_test_secret';
  const enqueued = [];
  const service = await startService({ apiKeys: [{ key: 'rk_paid_flow_owner_12345', accountId: 'acme', plan: 'unpaid', role: 'owner' }], billingSecret: secret, accountStore, store, worker: { enqueue(job) { enqueued.push(job); }, shutdown: async () => true }, port: 0, auditFile: path.join(root, 'audit.jsonl') });
  const base = `http://127.0.0.1:${service.address.port}`;
  const event = { id: 'evt_single_1', type: 'checkout.session.completed', data: { object: { id: 'cs_1', customer: 'cus_1', payment_status: 'paid', client_reference_id: 'acme', metadata: { accountId: 'acme', plan: 'single' } } } };
  const raw = JSON.stringify(event);
  const timestamp = Math.floor(Date.now() / 1000);
  const signature = createHmac('sha256', secret).update(`${timestamp}.${raw}`).digest('hex');
  const billing = await fetch(`${base}/webhooks/billing`, { method: 'POST', headers: { 'billing-signature': `t=${timestamp},v1=${signature}` }, body: raw });
  assert.equal(billing.status, 200);
  const duplicateBilling = await fetch(`${base}/webhooks/billing`, { method: 'POST', headers: { 'billing-signature': `t=${timestamp},v1=${signature}` }, body: raw });
  assert.equal((await duplicateBilling.json()).deduplicated, true);
  assert.equal(accountStore.get('acme').migrationCredits, 1);
  const headers = { authorization: 'Bearer rk_paid_flow_owner_12345', 'content-type': 'application/json', 'idempotency-key': 'paid-job-request-1' };
  const body = JSON.stringify({ repository: { fullName: 'acme/app' }, target: 'react-native' });
  const missingKey = await fetch(`${base}/v1/jobs`, { method: 'POST', headers: { authorization: headers.authorization, 'content-type': headers['content-type'] }, body });
  assert.equal(missingKey.status, 400);
  assert.equal(accountStore.get('acme').migrationCredits, 1);
  const created = await fetch(`${base}/v1/jobs`, { method: 'POST', headers, body });
  assert.equal(created.status, 202);
  assert.equal(enqueued.length, 1);
  assert.equal((await accountStore.get('acme')).migrationCredits, 0);
  const retried = await fetch(`${base}/v1/jobs`, { method: 'POST', headers, body });
  assert.equal(retried.status, 200);
  assert.equal((await retried.json()).deduplicated, true);
  assert.equal(enqueued.length, 1);
  const blocked = await fetch(`${base}/v1/jobs`, { method: 'POST', headers: { ...headers, 'idempotency-key': 'paid-job-request-2' }, body });
  assert.equal(blocked.status, 402);
  await service.close();
});
