const state={token:sessionStorage.getItem('repo-upgrader-token')||'',jobs:[],timer:null};
const $=(id)=>document.getElementById(id);

$('connect-form').addEventListener('submit',async(event)=>{event.preventDefault();state.token=$('api-key').value.trim();sessionStorage.setItem('repo-upgrader-token',state.token);await load();});
$('refresh').addEventListener('click',load);
$('close-dialog').addEventListener('click',()=>$('job-dialog').close());
$('jobs').addEventListener('click',(event)=>{const row=event.target.closest('[data-job]');if(row)openJob(row.dataset.job);});
$('job-detail').addEventListener('click',async(event)=>{const cancel=event.target.closest('[data-cancel]');if(cancel){await api(`/v1/jobs/${cancel.dataset.cancel}`,{method:'DELETE'});$('job-dialog').close();await loadData();}const report=event.target.closest('[data-report]');if(report)downloadReport(report.dataset.report);});
$('job-form').addEventListener('submit',async(event)=>{event.preventDefault();message('Starting migration…');try{const job=await api('/v1/jobs',{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify({repository:{fullName:$('repository').value.trim()},target:$('target').value})});message(`Migration queued: ${job.id}`);event.target.reset();await loadData();}catch(error){message(error.message,true);}});
$('upload-form').addEventListener('submit',async(event)=>{event.preventDefault();const file=$('project-zip').files[0];const status=$('upload-message');if(!file)return;if(file.size>10*1024*1024){status.textContent='ZIP must be 10 MB or smaller.';status.classList.add('error');return;}status.textContent='Scanning and converting without running project code…';status.classList.remove('error');try{const headers={'content-type':'application/zip'};if(state.token)headers.authorization=`Bearer ${state.token}`;const response=await fetch(`/v1/upload-migrations?target=${encodeURIComponent($('upload-target').value)}`,{method:'POST',headers,body:file});if(!response.ok){const value=await response.json();throw new Error(value.error||`Upload failed (${response.status})`);}const blob=await response.blob();const disposition=response.headers.get('content-disposition')||'';const filename=disposition.match(/filename="([^"]+)"/)?.[1]||'migrated-project.zip';const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url);status.textContent='Migration complete. Your ZIP download has started.';}catch(error){status.textContent=error.message;status.classList.add('error');}});

async function api(path,options={}){const headers={...options.headers};if(state.token)headers.authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const body=await response.json();if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body;}
async function load(){if(!state.token&&!state.demo)return;try{await loadData();$('connect-card').hidden=true;$('workspace').hidden=false;$('connection').textContent=state.demo?'Demo connected':'Connected';$('connection').classList.add('online');if(state.demo)message('Public preview: repositories are not cloned or executed; jobs demonstrate the hosted workflow.');}catch(error){sessionStorage.removeItem('repo-upgrader-token');$('connection').textContent='Connection failed';$('connection').classList.remove('online');message(error.message,true);}}
async function loadData(){const[usage,analytics,jobs]=await Promise.all([api('/v1/usage'),api('/v1/analytics'),api('/v1/jobs?limit=20')]);state.jobs=jobs.jobs;$('month-count').textContent=`${usage.periodJobs} / ${Number.isFinite(usage.entitlements.monthlyJobs)?usage.entitlements.monthlyJobs:'∞'}`;$('success-rate').textContent=analytics.successRate===null?'—':`${Math.round(analytics.successRate*100)}%`;$('plan').textContent=usage.plan;$('total-count').textContent=analytics.totalMigrations;renderJobs(state.jobs);clearTimeout(state.timer);if(state.jobs.some(job=>['queued','running'].includes(job.status)))state.timer=setTimeout(loadData,5000);}
function renderJobs(jobs){$('jobs').innerHTML=jobs.length?jobs.map(job=>`<div class="job" data-job="${escape(job.id)}" tabindex="0"><div><strong>${escape(job.repository?.fullName||job.repositoryPath||'Local repository')}</strong><small>${label(job.target)} · ${new Date(job.createdAt).toLocaleString()}</small></div><span class="badge ${escape(job.status)}">${escape(job.status)}</span></div>`).join(''):'<p class="empty">No migrations yet.</p>';}
async function openJob(id){const job=await api(`/v1/jobs/${id}`);$('detail-title').textContent=job.repository?.fullName||'Migration details';const actions=[];if(['queued','awaiting-github-app'].includes(job.status))actions.push(`<button class="danger" data-cancel="${escape(job.id)}">Cancel migration</button>`);if(job.report)actions.push(`<button class="secondary" data-report="${escape(job.id)}">Download report</button>`);if(job.delivery?.pullRequestUrl)actions.push(`<a class="link" href="${escape(job.delivery.pullRequestUrl)}" target="_blank" rel="noopener">Open pull request</a>`);$('job-detail').innerHTML=`<div class="detail-grid"><div><span>Status</span><strong>${escape(job.status)}</strong></div><div><span>Target</span><strong>${label(job.target)}</strong></div><div><span>Created</span><strong>${new Date(job.createdAt).toLocaleString()}</strong></div><div><span>Job ID</span><strong>${escape(job.id.slice(0,8))}…</strong></div></div><h3>Lifecycle</h3><ol class="timeline">${(job.events||[]).map(item=>`<li><strong>${escape(item.status)}</strong><br><small>${new Date(item.at).toLocaleString()}</small></li>`).join('')}</ol>${job.error?`<p class="message error">${escape(job.error)}</p>`:''}<div class="dialog-actions">${actions.join('')}</div>`;$('job-dialog').showModal();}
async function downloadReport(id){try{const report=await api(`/v1/jobs/${id}/report`);const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`migration-${id}.json`;link.click();URL.revokeObjectURL(url);}catch(error){message(error.message,true);}}
function label(target){return {vite:'CRA → Vite',nextjs:'React → Next.js','react-native':'React → React Native'}[target]||target;}
function message(value,error=false){$('message').textContent=value;$('message').classList.toggle('error',error);}
function escape(value){const node=document.createElement('span');node.textContent=String(value);return node.innerHTML;}
async function initialize(){try{const config=await fetch('/v1/demo-config').then(response=>response.json());state.demo=config.enabled===true;}catch{}if(state.demo||state.token)load();}
initialize();
